[package]
name = "tiny-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.2"
num-dual = "0.7.1"
num-traits = "0.2.15"

[[example]]
name = "example_solve"
crate-type = ["bin"]
