[package]
name = "tiny-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.32.4", features = ["sparse"] }
nalgebra-sparse = "0.9.0"
num-dual = "0.8.1"
num-traits = "0.2.18"

[[example]]
name = "example_solve"
crate-type = ["bin"]

[dev-dependencies]
plotters = "0.3.5"

# [profile.release]
# debug = true