[package]
name = "tiny-solver"
version = "0.3.4"
edition = "2021"
authors = ["Powei Lin <poweilin1994@gmail.com>"]
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "Factor graph solver"
homepage = "https://github.com/powei-lin/tiny-solver-rs"
repository = "https://github.com/powei-lin/tiny-solver-rs"
keywords = ["factor-graph", "ceres-solver", "minisam"]
categories = ["data-structures", "science", "mathematics"]
exclude = ["/.github/*", "*.ipynb", "./scripts/*", "examples/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faer = "0.18.2"
faer-ext = { version = "0.1.0", features = ["nalgebra"] }
nalgebra = "0.32.4"
num-dual = "0.8.1"
num-traits = "0.2.18"
numpy = { version = "0.20.0", features = ["nalgebra"] }
pyo3 = { version = "0.20.3", features = ["abi3", "abi3-py38"] }
rayon = "1.9.0"

[[example]]
name = "m3500_benchmark"
# crate-type = ["bin"]
path = "examples/m3500_benchmark.rs"

[dev-dependencies]
plotters = "0.3.5"

[profile.dev.package.faer]
opt-level = 3

[lib]
name = "tiny_solver"
# crate-type = ["cdylib"]
