[package]
name = "tiny-solver-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faer-core = "0.9.1"
faer-lu = "0.9.1"
nalgebra = "0.32.2"
num-traits = "0.2.15"

[[example]]
name = "t0"
crate-type = ["bin"]